### ISSUE TITLE
Body is deleted in new designer on the "Populate a Microsoft Word template" connector during dynamic content failure

### ISSUE THREAD

**Issue by JonMarr** [Azure/LogicAppsUX#2475]
### Describe the Bug with repro steps

Open any Logic App with the NEW designer that has a  "Word Online" - "Populate a Microsoft Word template" connector. The new designer deletes the "Body" when saved.

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using Preview Designer or GA Designer

Generally Available

### Workflow JSON

```json
{
    "definition": {
        "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
        "actions": {
            "Populate_a_Microsoft_Word_template": {
                "inputs": {
                    "body": {
                        "20141358": "IsProjKnownHazSite",
                        "113257481": "EnvSvcContact",
                        "118272026": "IsProjListedHistoric",
                        "134691988": "ProjectTitle",
                        "170303879": "LMIAreaBenefit",
                        "181859151": "IsProjFloodHazardWetland",
                        "188799541": "WhatyLevelEnvRevNeeded",
                        "229743537": "MaxNumActivitiesPerPRoj",
                        "248251066": "EnvSvcPhone",
                        "396088562": "TotalBeneHispanicNonHispanic",
                        "542560914": [
                            {
                                "ActivityTotal": "ActivityTotal ",
                                "PlanedReqAmount": "PlanedReqAmount ",
                                "ProgBudgetCode": "BLIRow  ProgBudgetCode ",
                                "TotalOtherFunds": "TotalOtherFunds "
                            }
                        ],
                        "649177840": "HaveThirdPartyEng",
                        "663902790": "WillProposedProjHaveNegImpactEnvPerHUDRegsNarative",
                        "764960077": "LMIBeneficiaries",
                        "835190117": "LMILimitedClientele",
                        "919217692": "EngCompanyName",
                        "975189298": "CurrentStatusOfProject",
                        "993922050": "IsProjReqHistoricalAssessNarative",
                        "1280071160": "IsProjOnFedLands",
                        "1323471780": "IsProjFloodplainRestActivity",
                        "1345745016": "ProgramName",
                        "1528284553": "TotalBeneNonHispanic",
                        "1584639642": "VendorCompanyName",
                        "1623810219": "TotalEstOrigProjBudget",
                        "1630289811": [
                            {
                                "DocTemplate": "DocTemplate",
                                "FileName": "UploadedDocs FileName ",
                                "FileSize": "FileSize"
                            }
                        ],
                        "1779294320": "VendorPhone",
                        "1931149229": "DoesBenefitLowIncomeOrUrgentNeed",
                        "1942799663": "ProjectSummary",
                        "1944957667": "EngCompanyContact",
                        "1963686038": "WillProposedProjHaveNegImpactEnvPerHUDRegs",
                        "2096278517": "HaveThirdPartyEnvService",
                        "2111620322": "IsProjListedHistoricNarrative",
                        "-1062859198": "AdditionalEnvRevDetail",
                        "-108354632": "MaxTotalAmountReq",
                        "-1136713958": "IsProjReqHistoricalAssess",
                        "-1142801720": "EnvSvcCompanyName",
                        "-1391568146": "EngEmail",
                        "-1404745407": "IsProjOnFedLandsNarrative",
                        "-1414470050": "SurveyBeginDate",
                        "-1581511338": "SelectBenIDMethodUsedNatObj",
                        "-1607333503": "IsProjCompliantOrder11990",
                        "-1616982142": "LMIHousingActivity",
                        "-1625229510": "ContractName",
                        "-1722741827": "TotalBeneficiaries",
                        "-1784178621": "PercentLMIBeneficiaries",
                        "-1823189387": "WillVendorProvideEnvServices",
                        "-2049751698": "ProvideExplainUseSurveyNotLMISD",
                        "-2092145595": "IsAppPartInNatFloodInsProgram",
                        "-2103165627": "EnvSvcEmail",
                        "-2146031876": "EngPhone",
                        "-317419491": [
                            {
                                "ERRNumber": "ERRRow ERRNumber ",
                                "ERRTitle": "ERRTitle ",
                                "LevelReview": "LevelReview ",
                                "ReviewStatus": "ReviewStatus "
                            }
                        ],
                        "-328132547": "MinTotalAmountReq",
                        "-427732243": "IsProjCriticalHabEndangeredSpecies",
                        "-432660957": [
                            {
                                "433638470": "ScheduleRow PhaseStatus ",
                                "EndDate": "EndDate ",
                                "Length": "Length ",
                                "ProjectPhase": "ProjectPhase ",
                                "StartDate": "StartDate "
                            }
                        ],
                        "-571743638": "VendorEmail",
                        "-582760911": "SurveyCompleteDate",
                        "-612594385": "IsProjDesRegFloodway",
                        "-760599626": "VendorContact",
                        "-774094496": "HaveThirdPartyAdmin",
                        "-853498203": "TotalBeneHispanic"
                    },
                    "host": {
                        "connection": {
                            "referenceName": "wordonlinebusiness_1"
                        }
                    },
                    "method": "post",
                    "path": "/api/templates/getFile",
                    "queries": {
                        "drive": "b!wju39imMqEKIrObHdubQFamFTjFnf1pLpeoa7S2m3LTo2o_-vbRSQo9Zmij8slKS",
                        "file": "012ITJQX2S5KLWBYAMEBBKYEU6T3HBHQTA",
                        "source": "sites/texasrebuilds.sharepoint.com,f6b73bc2-8c29-42a8-88ac-e6c776e6d015,314e85a9-7f67-4b5a-a5ea-1aed2da6dcb4"
                    }
                },
                "metadata": {
                    "012ITJQX2S5KLWBYAMEBBKYEU6T3HBHQTA": "/DocGenProcessing/Templates/ProjectMitTemplatePortal.docx"
                },
                "runAfter": {},
                "type": "ApiConnection"
            }
        },
        "contentVersion": "1.0.0.0",
        "outputs": {},
        "triggers": {
            "manual": {
                "inputs": {},
                "kind": "Http",
                "type": "Request"
            }
        }
    },
    "kind": "Stateful"
}
```

### Browser

Chrome and Edge

**Comment by preetriti1** [comment]
@JonMarr - I am not seeing this issue in PROD portal, do you mind checking if you are getting any erros in network tab or console logs?

**Comment by JonMarr** [comment]
I have Logic Apps that have been running for a year or so. I was able to edit them in the old Designer two weeks ago. I could open and save without losing any code. These Logic Apps use the Word Online "Populate a Microsoft Word template" action. All properties are expressions. When the designer opens it will not find the file in SharePoint. Which is fine because the old designer didn't wipe out the Body when that happened. At run time the expressions are valid and the SharePoint paths are correct, so it all works.

In the new designer the "Populate a Microsoft Word template" action, when opened deletes the "Body" parameter if it can't connect to SharePoint. You can see that the body is missing in the "Code View". Then when you save, the body that was in the code is gone. This is because it can't fine the SharePoint file.

It looks like when the new properties window opens for the "Populate a Microsoft Word template" action, if it can't connect to the SharePoint template file it clears the Body. I have expressions for the Location, Doc Library, and File values. This is why it can't connect. The old Properties window did not wipe out the "Body" if it could not connect.


Console Error:
There is one 404 error in console when the Logic App loads in the designer. It's a 404 error because the "Populate a Microsoft Word template" action can't find the Word document in SharePoint. This is expected since the action does not have valid values to find the file.


Here is an example JSON app. Add it to new standard Logic App. Look at the code view, there is a Body in the "Populate_a_Microsoft_Word_template" action. Now open it in the new designer, change some value (I just change the name of the action), then save and the Body will be deleted. The old designer did not delete the body.

NOTE: You won't have the connection or permissions to connect with this code. But this is exactly why the new designer breaks the code. The old designer would show the connection error, but at least it did not delete code when saved.


{
    "definition": {
        "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
        "actions": {
            "Populate_a_Microsoft_Word_template": {
                "inputs": {
                    "body": {
                        "20141358": "IsProjKnownHazSite",
                        "113257481": "EnvSvcContact",
                        "118272026": "IsProjListedHistoric",
                        "134691988": "ProjectTitle"
                    },
                    "host": {
                        "connection": {
                            "referenceName": "wordonlinebusiness_1"
                        }
                    },
                    "method": "post",
                    "path": "/api/templates/getFile",
                    "queries": {
                        "drive": "b!wju39imMqEKIrObHdubQFamFTjFnf1pLpeoa7S2m3LTo2o_-vbRSQo9Zmij8slKS",
                        "file": "012ITJQX2S5KLWBYAMEBBKYEU6T3HBHQTA",
                        "source": "sites/texasrebuilds.sharepoint.com,f6b73bc2-8c29-42a8-88ac-e6c776e6d015,314e85a9-7f67-4b5a-a5ea-1aed2da6dcb4"
                    }
                },
                "metadata": {
                    "012ITJQX2S5KLWBYAMEBBKYEU6T3HBHQTA": "/DocGenProcessing/Templates/ProjectMitTemplatePortal.docx"
                },
                "runAfter": {},
                "type": "ApiConnection"
            }
        },
        "contentVersion": "1.0.0.0",
        "outputs": {},
        "triggers": {
            "manual": {
                "inputs": {},
                "kind": "Http",
                "type": "Request"
            }
        }
    },
    "kind": "Stateful"
}




________________________________

**Comment by preetriti1** [comment]
@JonMarr So what I get from above is -
1. There is a dynamic call failure since file is not found [the 404 you listed] on reloading the designer after the first save.
 So you see something like this - 
![image](https://github.com/Azure/LogicAppsUX/assets/48265693/65aad245-2791-4130-b01f-5eb7493e9986)

2. I did not understand the connection part? Do you have a connection failure as well?

If it is #1, we have a fix coming up for that scenario in our next release.

**Comment by JonMarr** [comment]
Yes on #1, that is what I see. When I said connection I was referring to #1. A bad choice of words on my part.

Thank you!

Very impressed by the quick response!




Jonathan Marr

443-995-4417

Sylogist<https://www.sylogist.com/>

[cid:42aaf67f-7988-411d-a9de-e6365e6493ea]


________________________________

**Comment by preetriti1** [comment]
Our next designer update probably in 2 weeks should have this fix or maybe included in any hotfixes that we are having before that.

**Comment by preetriti1** [comment]
@JonMarr - We have deployed fix in production for this today.

**Comment by JonMarr** [comment]
FYI:
The issue is still there. I forgot to mention I'm in the Gov cloud, portal.azure.us

Will Azure Government get the fix?

Thanks for your quick response!
________________________________
