### ISSUE TITLE
Workflow URL generated for Request Trigger with path parameters not correct. 

### ISSUE THREAD

**Issue by mohit-jagtiani** [Azure/LogicAppsUX#2557]
### Describe the Bug with repro steps

Create a new workflow on Portal with Request Trigger
Add relative path param
Save the workflow.
Check the workflow url.
In my case it is 

`https://la-esb-devtst-documentsapi-001.ase-esb-devtst-application-001.appserviceenvironment.net/documents/%7BdocumentId%7D/%7Brevision%7D/file?[Querry Params]`

Should have been
`https://la-esb-devtst-documentsapi-001.ase-esb-devtst-application-001.appserviceenvironment.net/api/get-doucument-file-from-efs/triggers/Get_Document_Request/invoke/documents%2F312%2F3%2Ffile?[Querry Params]`

Also run with payload bug is not fixed #2440
Probably related to #2439

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using Preview Designer or GA Designer

Generally Available

### Workflow JSON

```json
{
    "definition": {
        "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
        "actions": {},
        "contentVersion": "1.0.0.0",
        "outputs": {},
        "triggers": {
            "Get_Document_Request": {
                "inputs": {
                    "method": "GET",
                    "relativePath": "/documents/{documentId}/{revision}/file"
                },
                "kind": "Http",
                "type": "Request"
            }
        }
    },
    "kind": "Stateful"
}
```

### Browser

Firefox

**Comment by preetriti1** [comment]
@mohit-jagtiani - This issue is fixed in the Portal for standard workflows and we can also successfully invoke using RunWithPayload using your relative path.
![image](https://github.com/Azure/LogicAppsUX/assets/48265693/2e5856e0-8886-47f1-8338-005bbc914f05)

![image](https://github.com/Azure/LogicAppsUX/assets/48265693/5b3ed566-dded-47e2-b977-4f9245f08473)

The only issue I am seeing now is this extra path "api/get-doucument-file-from-efs/triggers/Get_Document_Request/invoke"
not included in the url shown in UI, so we will keep this issue to track it. But Run With payload works in the portal

**Comment by preetriti1** [comment]
We have deployed today with the fix for the missing part in path in the url generated. No change made in runwithpayload. Please reopen the issue if your runwithpayload still fails and do provide screenshots on what you are seeing in the results

**Comment by mohit-jagtiani** [comment]
Run with payload on portal is still not working

![image](https://github.com/Azure/LogicAppsUX/assets/64312140/dbf903f5-66fb-4801-89e8-22a27a0ac1e7)

**Comment by preetriti1** [comment]
@mohit-jagtiani - Please open a CSS ticket or ICM on this so you can share your logs [network traces/console logs] to investigate further on what is going wrong with your app run here.
