### ISSUE TITLE
Logic App Sql Connector  Failed to retrieve dynamic inputs. Error details: ''

### ISSUE THREAD

**Issue by yasarqamar** [Azure/LogicAppsUX#2955]
### Describe the Bug with repro steps

Logic App 'Execute a SQL query (V2)' connector is unable to to retrieve dynamic inputs

![LogicAppIssue](https://github.com/Azure/LogicAppsUX/assets/12909195/66ddbd1a-ffe1-4bbb-8967-b8d712fce468)

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Screenshots or Videos

![image](https://github.com/Azure/LogicAppsUX/assets/12909195/081ef9a2-c175-4333-9af3-c1a7db02f2fe)

### Browser

Chrome

AB#24518913

**Comment by rllyy97** [comment]
Hi @yasarqamar, thank you for the bug report!  We recently released a dynamic data fix for the broader issue mentioned here https://github.com/Azure/LogicAppsUX/issues/2949, and I am fairly confident this issue has the same root cause.  I am going to close this issue, but feel free to try out your use case and if you are still experiencing issues let us know and we can reopen and investigate further.

**Comment by yasarqamar** [comment]
Hi @rllyy97,

Thanks for your response, however, the issue still persists as per below

![LogicAppIssue_Persists](https://github.com/Azure/LogicAppsUX/assets/12909195/0d06e333-3fed-4d39-8954-048fa7ec305f)

**Comment by rllyy97** [comment]
Thanks for the follow up @yasarqamar.  For me to look into this further I have a couple things from you that would help.
First I'd like to get a network trace of you adding the action and trying to select the dynamic data, you can find steps on how to do that in our documentation located here:
https://purple-pebble-0e11de71e.1.azurestaticapps.net/tsg#collecting-network-logs-in-a-har-file
Once you have the `.har` file you can send it to me at rileyevans@microsoft.com

Second, I'd like you to try your same use-case on legacy designer to see the issue is still occurring, you can find steps on how to access legacy designer here:
https://purple-pebble-0e11de71e.1.azurestaticapps.net/tsg#fallback-to-legacy-designer

**Comment by yasarqamar** [comment]
Hi @rllyy97,
I have used the legacy designer and it doesn't present this issue which indicates it is to do with the New Designer.
However, until recently i was able to work fine in the New Designer as well.

I'll see if I'm able to capture a trace.

**Comment by yasarqamar** [comment]
Hi @rllyy97,
I can confirm that the  New designer is also working fine now. I had to do a browser restart to get rid of the cache

**Comment by rllyy97** [comment]
Oh great!  Glad to hear that, if your issues are all fixed now I'm going to close the issue, thanks for your cooperation while we got this resolved

**Comment by csanghavi** [comment]
I am still having this issue. The values are not populating when using Connection defined using Managed Identity.

**Comment by rllyy97** [comment]
Hi @csanghavi, we've fixed this issue as part of our upcoming release, rollout will finish by this Friday (July 28th).  Let us know if you're still running into issues after the 28th

**Comment by Akshat59** [comment]
still facing this issue

**Comment by Vegas08** [comment]
Make sure you are using the correct account in the action 

<img width="700" alt="Image" src="https://github.com/user-attachments/assets/62dbaf6b-3629-40f2-b178-00593066492c" />

**Comment by Vegas08** [comment]
Still not functioning. I can get the server var to work but not the database var.
 
Found a workaround :) 

Put the env variable in a flow variable and use the flow variable in the sql action
