### ISSUE TITLE
Custom: Unable to fetch custom connectors operations

### ISSUE THREAD

**Issue by vgouth** [Azure/LogicAppsUX#5787]
### Describe the Bug with repro steps 

1. Create a custom connector with sentiment.json file. 
2. Create a LogicApp in the same subscription and same location as your customConnector created. (I have created both in West central US location) 
3. Go to Edit blade for your Logic App 
4. You should see your custom connector and its operations in the recommendation card when filter runtime with custom as trigger. 

**Expected:** Created custom connectors in the same subscription and same region should be found when we filter runtime with custom.

**Actual:** Unable to fetch custom connectors operations

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Which operating system are you using? 

Windows

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

[https://github.com/user-attachments/assets/8df8ee3e-d102-480a-9bb1-56dad7125c85](<https://github.com/user-attachments/assets/8df8ee3e-d102-480a-9bb1-56dad7125c85>)

### Browser 

Edge

### Additional context 

**Version:** 0\.2022.1.764

**Comment by preetriti1** [comment]
@vgouth - Please send me an email with the network logs captured before you open the designer and until you observe the issue.. 
Faster would be keep the repro in the logic app and do not delete it, and give me access so i can look at it

**Comment by vgouth** [comment]
Issue still repro in the latest build. 

**Version:** 2.41007.1.5

@preetriti1 Given you contributor access to logic app custom connector and logic app.

**Comment by rllyy97** [comment]
This is fixed in 2.41007.1.9 and above, just verified in staging that this is working.

**Comment by simenums** [comment]
@rllyy97 @vgouth @Eric-B-Wu  @preetriti1 : We still experience this issue. This is issue is much more serious from today since the legacy designer is not available anymore ! When is deployment of fix planned?

**Comment by rllyy97** [comment]
Hi @simenums, can you try two things for me, they might help unblock you.  
I'm currently seeing that the browse (no search input) is not working as expected in all scenarios for  custom connectors, but if I search I am able to see my custom actions/triggers.
Please also try unchecking the `Action Type` filters so none are selected.  This also made the custom actions/triggers appear for me in search.
We are looking into what caused this and will update you when we have an ETA on a fix!

**Comment by vgouth** [comment]
@rllyy97 Issue repro in latest test pass. Unable to fetch connectors when we search/ filter with custom runtime.
**Version :** : 2.41028.1.2
 
![Image](https://github.com/user-attachments/assets/427e5ff7-b943-4888-ab6c-40fbcf8debfa)
![Image](https://github.com/user-attachments/assets/bd32ab16-0418-48f2-aa99-ae91c81c46d1)

**Comment by vgouth** [comment]
@rllyy97 Issue repro in latest test pass. Unable to fetch connectors as triggers when we search/ filter with custom runtime. 
Able to fetch custom connectors in actions while filtering with custom runtime and also when we search without filtering with custom runtime. 

Version : : 2.41028.1.6

![Image](https://github.com/user-attachments/assets/e15013cf-0998-4773-890e-d8680e20d511)
![Image](https://github.com/user-attachments/assets/3537afd4-87db-433e-ba1f-f8efd732c00a)

**Comment by rllyy97** [comment]
@vgouth Can you try to repro in staging again?  Staging is running `2.41028.1.12` and I'm not able to reproduce this issue.
Browse shows the connector:
![Image](https://github.com/user-attachments/assets/46c28f2e-0eb6-4915-93aa-b72bc9604a77)

And searching for the action also shows results:
![Image](https://github.com/user-attachments/assets/f4b3e93b-2fa5-4d8b-8be2-b647d305c92c)

**Comment by vgouth** [comment]
@rllyy97. In the last staging request with version **0.2022.1.796**, I was unable to create logic apps custom connectors. Currently, I am still facing the same issue. I will re-evaluate this in the next staging version. If the issue is resolved, I will close it with a comment.

![Image](https://github.com/user-attachments/assets/9398afd6-6243-4d39-b32f-a5ef982af0a7)

**Comment by vgouth** [comment]
@rllyy97 Issue repro in latest canary test pass
**Version:** 0.2022.1.806
![Image](https://github.com/user-attachments/assets/38b5bb7a-640b-45b2-83e9-e2631f59a72f)

**Comment by vgouth** [comment]
Issue repro in latest canary test pass
**Version:** 0.2022.1.811

**Comment by vgouth** [comment]
Issue repro in latest canary test pass
**Version:** 0.2022.1.811

**Comment by vgouth** [comment]
@rllyy97 Issue repro in latest staging test pass.Unable to fetch connectors as triggers when we search/ filter with custom runtime.
Able to fetch custom connectors in actions while filtering with custom runtime and also when we search without filtering with custom runtime.
**Version:** 2.50107.1.3

![Image](https://github.com/user-attachments/assets/7a181712-b9f0-424e-bc90-4334d62f961a)

![Image](https://github.com/user-attachments/assets/19674c74-4d1d-4272-9f77-82ddf2611829)

**Comment by vgouth** [comment]
@rllyy97 Issue repro in latest staging test pass.Unable to fetch connectors as triggers when we search with custom connector name/ filter with custom runtime.
Able to fetch custom connectors in actions while filtering with custom runtime and also when we search with custom connector name without filtering with custom runtime.

**Version:** 2.50203.1.2
![Image](https://github.com/user-attachments/assets/5265df49-54d3-42ef-a411-6431587168c7)

![Image](https://github.com/user-attachments/assets/177106c9-8f0e-4c95-8b62-7f4eb38130cc)

**Comment by vgouth** [comment]
@rllyy97 
Issue repro in latest canary test pass
**Version:** 2.0.20250210.1

![Image](https://github.com/user-attachments/assets/5490761e-1d49-4973-b45c-f0476c398812)

![Image](https://github.com/user-attachments/assets/f34a110a-bcb0-4516-ad77-e87373adebf0)

**Comment by vgouth** [comment]
@rllyy97 
Issue repro in latest staging test pass,Unable to fetch connectors as triggers when we search with custom connector name/ filter with custom runtime.
Able to fetch custom connectors in actions while filtering with custom runtime and also when we search with custom connector name without filtering with custom runtime.
**Version:** 2.50324.1.5

![Image](https://github.com/user-attachments/assets/1bb1bc2d-38a8-4fe3-9022-9fb0a5e18199)

**Comment by vgouth** [comment]
@rllyy97 
Issue repro in latest canary test pass, Unable to fetch connectors as triggers when we search with custom connector name/ filter with custom runtime.
Able to fetch custom connectors in actions while filtering with custom runtime and also when we search with custom connector name without filtering with custom runtime.

**Version:** 2.0.20250408.2

![Image](https://github.com/user-attachments/assets/bacdab55-3242-43ea-b08c-117ca2a02389)

![Image](https://github.com/user-attachments/assets/20e46085-c153-44c3-a697-2afeaba13db1)

**Comment by vgouth** [comment]
@rllyy97 
Issue repro in latest staging test pass. Unable to fetch connectors as triggers when we search/ filter with custom runtime.
Able to fetch custom connectors in actions while filtering with custom runtime and also when we search without filtering with custom runtime.

**Version:** 2.50425.1.3

![Image](https://github.com/user-attachments/assets/00d25afe-6cb3-46de-90bd-bfa16f6984d2)

**Comment by vgouth** [comment]
@rllyy97
Issue repro in latest canary test pass. Unable to fetch connectors as triggers when we search/ filter with custom runtime.
Able to fetch custom connectors in actions while filtering with custom runtime and also when we search without filtering with custom runtime.

**Version:** 2.0.20250512.2

![Image](https://github.com/user-attachments/assets/ad0f4bc5-8c38-4212-8683-ae81bb3a306c)

**Comment by vgouth** [comment]
@rllyy97
Issue repro in latest staging test pass. Unable to fetch connectors as triggers when we search/ filter with custom runtime.
Able to fetch custom connectors in actions while filtering with custom runtime and also when we search without filtering with custom runtime.
**Version:** 2.50522.1.10
![Image](https://github.com/user-attachments/assets/2542762e-147e-4f4f-876d-03d97ed009a0)

**Comment by vgouth** [comment]
Issue repro in latest canary test pass
**Version:** 2.0.20250604.1
![Image](https://github.com/user-attachments/assets/3e04884b-68ba-4320-9652-2c87700de080)

**Comment by vgouth** [comment]
@rllyy97
Issue repro in latest staging test pass. Unable to fetch connectors as triggers when we search/ filter with custom runtime.
Able to fetch custom connectors in actions while filtering with custom runtime and also when we search without filtering with custom runtime.
**Stage Version:** 2.50616.1.1

![Image](https://github.com/user-attachments/assets/ef004a4d-9ea9-4b3b-ae01-47d381b91aa9)
