### ISSUE TITLE
Options like "host.json" and "local.settings.json" under workflow_designtime are not appearing as expected.

### ISSUE THREAD

**Issue by vgouth** [Azure/LogicAppsUX#6824]
### Describe the Bug with repro steps 

1. Create a workspace in Vs code 
2. Create a new logic app project under it 
3. Once the project is created, we should see the "Use connectors from Azure" option within a minute. However, we are unable to see this option until we click on the Open designer option. After seeing the "Use Connectors from Azure" option, we should see "host.json" and "local.settings.json" under workflow\_designtime, but this is also not happening. We have to kill the existing function, close the opened designer, and then click on Open designer again to see "host.json" and "local.settings.json" under workflow\_designtime. 

### What type of Logic App Is this happening in? 

Standard (VSCode)

### Which operating system are you using? 

Windows

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

```json

```

### Screenshots or Videos

[https://github.com/user-attachments/assets/fb549656-ff19-4f1e-9296-a535778cd99d](<https://github.com/user-attachments/assets/fb549656-ff19-4f1e-9296-a535778cd99d>)

### Browser

VS Code

### Additional context

**VSIX Version:** 5\.44.5

**Comment by vgouth** [comment]
Issue repro in latest VS Code test pass
**VSIX Version :** 5.58.0

**Comment by vgouth** [comment]
Issue repro in latest VS Code test pass
**VSIX Version :** 5.58.4

**Comment by vgouth** [comment]
Issue repro in the latest VS code test pass. 

**VSIX Version:** 5.94.0

**Comment by vgouth** [comment]
Issue repro in latest VS code test pass
**VSIX Version:** 5.94.17

**Comment by vgouth** [comment]
Issue repro in latest VS code test pass.

**VSIX Version:** 5.109.13

**Comment by ccastrotrejo** [comment]
This issue gets fixed with the following PR - https://github.com/Azure/LogicAppsUX/pull/7564

**Comment by vgouth** [comment]
@ccastrotrejo 
Issue repro in latest VS code test pass. Looks like the issue is not fixed yet. Request to re-open the bug

VSIX Version: 5.130.5

**Comment by vgouth** [comment]
@ccastrotrejo 
Issue repro in latest VS code test pass. Looks like the issue is not fixed yet. Request to re-open the bug

**Production VSIX version:** 5.130.9

**Comment by vgouth** [comment]
@ccastrotrejo 
Issue repro in latest VS code test pass. 

**VSIX Version:** 5.165.0

**Comment by andrew-eldridge** [comment]
@vgouth just to clarify, in the latest repro do the `host.json` and `local.settings.json` get created once the designer is opened for the new project? I am able to repro the part of the issue where 'Use connectors from Azure' is not automatically prompted for the new project and design-time api isn't started until designer is opened, but I'm still seeing `host.json` and `local.settings.json` created under workflow-designtime when designer is opened

**Comment by vgouth** [comment]
@andrew-eldridge 
Issue repro in latest VS code test pass.
VSIX version: 5.230.14(re-test)

After creating a new logic app project, clicking on workflow.json ->open designer shows host.json and local.settings.json under workflow-designer time.

**Comment by vgouth** [comment]
Issue repro in latest VS Code test pass.
VSIX Version : 5.203.14
Bundle Version : 1.156.1

After creating a new logic app project, clicking on workflow.json ->open designer shows host.json and local.settings.json under workflow-designer time.

**Comment by v-ksruthi** [comment]
Issue repro in latest VS Code test pass.
VSIX Version : 5.230.15
Bundle Version : 1.160.2

**Comment by v-ksruthi** [comment]
Issue repro in latest VS Code test pass.
VSIX Version : 5.273.0
Bundle Version : 1.161.3

<img width="315" height="327" alt="Image" src="https://github.com/user-attachments/assets/3ed1b0e3-d5f3-4ccf-bf92-11f7cc7ae798" />

**Comment by v-ksruthi** [comment]
Issue repro in latest VS Code test pass.
VSIX Version : 5.273.0
Bundle Version : 1.165.2

<img width="288" height="275" alt="Image" src="https://github.com/user-attachments/assets/6cdf9c8e-f640-4769-b585-2b6ee6a997c2" />

**Comment by vgouth** [comment]
Issue repro in latest VS code test pass.

VSIX Version : 5.956.0
Bundle Version : 1.165.9

**Comment by v-ksruthi** [comment]
Issue repro in latest VS code test pass.

VSIX Version : 5.959.0
Bundle Version : 1.170.3

<img width="287" height="243" alt="Image" src="https://github.com/user-attachments/assets/d345694c-1ab2-4f00-a76a-1740466ebb62" />

**Comment by v-ksruthi** [comment]
Issue repro in latest vscode request
VSIX Version:5.961.4
Bundle Version:1.170.3


<img width="215" height="140" alt="Image" src="https://github.com/user-attachments/assets/62a17df8-952a-48f4-a822-e2d7bdc316ac" />

**Comment by andrew-eldridge** [comment]
Closing as expected behavior, this is what is currently observed:
1. 'Use connectors from Azure' prompt no longer appears on new project creation, only when designer first opened or logic app run
2. When designer is opened, `workflow-designtime` is created with host.json and local.settings.json, design-time func starts, then 'Use connectors from Azure' prompt appears

Re-open if any deviation from the above
