### ISSUE TITLE
Quotes are added in compose for non-text fields

### ISSUE THREAD

**Issue by pfoolen** [Azure/LogicAppsUX#7252]
### Describe the Bug with repro steps

1. compose with value 15
2. second compose with a json with two properties. One has a value with text, the second should be a number and is set with the first compose (value 15)
3. Run logic app and the result is as expected
4. Edit the logic app. You now see that the second compose at the second json property value quotes are added
5. Make a small change in the second compose (change text) and save the logic app
6. If you run the logic app the second json propertyvalue is not a number but a string
7.

### What type of Logic App Is this happening in?

Consumption (Portal)

### Which operating system are you using?

Windows

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

No

### Workflow JSON

```json
{
    "definition": {
        "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
        "contentVersion": "1.0.0.0",
        "triggers": {
            "When_a_HTTP_request_is_received": {
                "type": "Request",
                "kind": "Http"
            }
        },
        "actions": {
            "Compose": {
                "type": "Compose",
                "inputs": 15,
                "runAfter": {}
            },
            "Compose_1": {
                "type": "Compose",
                "inputs": {
                    "name": "jacky",
                    "age": "@outputs('Compose')"
                },
                "runAfter": {
                    "Compose": [
                        "Succeeded"
                    ]
                }
            }
        },
        "outputs": {},
        "parameters": {
            "$connections": {
                "type": "Object",
                "defaultValue": {}
            }
        }
    },
    "parameters": {
        "$connections": {
            "type": "Object",
            "value": {}
        }
    }
}
```

### Browser

chrome

**Comment by Andrew-Lahikainen** [comment]
Seeing this as well. Pretty insidious - introducing a lot of subtle bugs. It'd be nice to know when this was introduced so I can lock my extension version.

**Comment by janikarkkainen** [comment]
I'm also seeing this, and it is very annying breaking the app totally in certain cases. For example, we are adding arrays variables into json objects used in http post actions, and randomly after saving the app includes them as string, breaking rest api payloads.

**Comment by oscar-pickering** [comment]
Also seeing this - please fix ASAP Microsoft!!!

**Comment by JoeBarisSpring** [comment]
This is huge for us, our whole team is affected. We are also seeing this on our side and totally bringing us to a standstill. This needs a fix ASAP

**Comment by bcrobinson** [comment]
I've made a screen recording that shows where this issue is happening:

https://github.com/user-attachments/assets/c0fef7ee-ff79-4d8a-b24a-8665a2620a6d

**Comment by Eric-B-Wu** [comment]
We're looking to get a hotfix change out for this; I'm currently creating a build and will hopefully have a link for testing in a couple of hours and to have this fully fixed by EOD today

**Comment by AnthonyDob** [comment]
Issue still occuring. When adding a compose output to a HTTP connectors json body property value it also enforces it in quotes while the values are objects. When is this getting fixed? This is interrupting development.. 

![Image](https://github.com/user-attachments/assets/1cc7fe87-0a31-4c83-b609-37ab257cd802)

**Comment by Liam-Rougoor** [comment]
I ran into the same issue. It does look alright in the staging link.
Non staging:

![Image](https://github.com/user-attachments/assets/59f6c13f-a58d-4b19-a55a-72879f4a2360)

Staging:

![Image](https://github.com/user-attachments/assets/eb20a2a1-a2ab-4505-aa06-a1262c57c7bd)

**Comment by Andrew-Lahikainen** [comment]
> We're looking to get a hotfix change out for this; I'm currently creating a build and will hopefully have a link for testing in a couple of hours and to have this fully fixed by EOD today

When do you think this will be fixed in the vscode extension?

**Comment by Liam-Rougoor** [comment]
@takyyon I haven't run into the issue anymore, it seems to be working fine. Thank you!
